config/routes.rb
Rails.application.routes.draw do
    post '/rate' => 'rater#create', :as => 'rate'
    get 'acceptions/create'

    devise_for :users, controllers: { registrations: "registrations"}
    root to: 'static_pages#home'
    resources :users do
        resource :info,only: [:show,:new,:create]
        resource :settings, only: [:show,:new,:create]
        resources :photos do
            resources :comments
        end
        resources :travels do
            resources :comments
        end
        resource :contacts

        resources :friendships do
            resource :acceptance , only: [:create, :destroy]
        end
        resources :friends, only: [:index]

        member do
            post "rate"
        end

    end

    resources :hotspots do
        resources :photos do
            resources :comments
        end
        resources :travels, only: [:index]
    end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  belongs_to :travel
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :friend1 , class_name: "User"
    belongs_to :friend2, class_name: "User"

    validates :friend1_id , presence: true
    validates :friend2_id , presence: true

    def accept!
        self.update_attributes(confirmed: true)
    end
end

app/models/heart.rb
class Heart < ActiveRecord::Base
    belongs_to :photo

    belongs_to :user

    validates :user_id , uniqueness: {scope: :photo_id}
end

app/models/hotspot.rb
class Hotspot < ActiveRecord::Base
    has_many :photos
    ratyrate_rateable "stars"
    validates :name, uniqueness: :true
    geocoded_by :address
    after_validation :geocode
    has_many :travels

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

end

app/models/info.rb
class Info < ActiveRecord::Base

  belongs_to :user
  # validates_format_of :dob, :with => /\A(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})\Z/ 




  def if_absent
      self
  end

  def if_present
      yield
      self
  end
end

app/models/noinfo.rb
class Noinfo
    def if_absent
        yield
        self
    end

    def if_present
        self
    end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :hotspot
  has_attached_file :pic, styles: {medium: "300x300", thumbnail: "100x100>", full: "500x500"}
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

  has_many :comments,dependent: :destroy
  default_scope -> {order(created_at: :desc)}

  def set_user(user)
      self.user = user
  end

  def set_hotspot(hotspot, user)
      self.hotspot = hotspot
      self.user = user
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/setting.rb
class Setting
    include ActiveModel::Model

    attr_accessor :info_fb, :info_dob, :info_city , :info_interests

    def save(info)
        info.update_attributes(dob: info_dob, city: info_city , interests: info_interests, fb: info_fb) 
    end
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :user
  has_attached_file :featured_image, styles: {medium: "600x600", thumbnail: "200x200>", full: "500x500"}
  validates_attachment_content_type :featured_image, :content_type => /\Aimage\/.*\Z/
  has_many :comments
  belongs_to :hotspot

  def set_user(user)
      self.user = user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    has_attached_file :avatar, styles: {medium: "300x300", thumbnail: "100x100>"}

    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    has_one :info
    has_many :photos
    has_many :comments,dependent: :destroy
    has_many :travels
    has_many :friendships
    ratyrate_rater

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

    def friends
        Friendship.where("friend1_id = ? OR friend2_id = ?",self.id,self.id)
    end


end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
    def index
        if on_user_path
            @user = User.find(params[:user_id])
            @travels = Travel.order('created_at').where(user_id: @user.id)
        else
            @hotspot = Hotspot.find(params[:hotspot_id])
            @travels = Travel.order('created_at').where(hotspot_id: @hotspot.id)
        end
    end

    def new
        @user = User.find(params[:user_id])
        @travel = Travel.new
    end

    def create
        @user = User.find(params[:user_id])
        @travel = Travel.new(travel_params)
        @travel.set_user(current_user)
        if @travel.save

            redirect_to user_travels_path(current_user)
        else
            flash[:notice] = "Travel wasn't saved"
            redirect_to root_path
        end
    end

    def show
        if on_user_path
            @user = User.find(params[:user_id])
            @travel = Travel.find(params[:id]) 
            @comment = Comment.new
        else
            @hotspot = Hotspot.find(@travel.hotspot_id)
            @user = User.find(params[:user_id])
            @comment = Comment.new
        end
    end


    private


    def travel_params
        params.require(:travel).permit(:featured_image,:title,:content,:hotspot_id)
    end

    def on_user_path
        request.original_fullpath.include?("users")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/travels/_hotpotravels.html.erb
<div class="container trav">
    <div class="row">
        <% if @travels.any?%>
            <% @travels.each_with_index do |travel|%>
                <ul>
                    <li>    <div class="card">
                            <div class="card-img-top" >
                                <%= link_to (image_tag travel.featured_image.url(:full)), user_travel_path(travel.user,travel)%>
                            </div>
                            <div class="card-block">
                                <center> <h1 class="lead"> <%= link_to travel.title, user_travel_path(travel.user,travel)%> </h1></center>
                                <%=link_to travel.user.name, user_path(travel.user)%>
                            </div>
                            </br>
                            </br>
                    </li>
                </ul>
            <%end%>
        <%end%>
                        </div>
    </div>
</div>

app/views/travels/index.html.erb
</br>
<% if on_hotspots_path %>
    <%= render 'travels/hotpotravels'%>
<% else%>
<div>
    <% if current_user == @user%>
        &nbsp;&nbsp;&nbsp;<%= link_to "New Travel", new_user_travel_path(@user), class: 'btn btn-success'%>
<%end%>
</div>
</br>
</br>
<hr>
<div class="container trav">
    <div class="row">
        <% if @travels.any?%>
            <% @travels.each_with_index do |travel|%>
                <ul>
                    <li>    <div class="card">
                            <div class="card-img-top" >
                                <%= link_to (image_tag travel.featured_image.url(:full)), user_travel_path(@user,travel)%>
                            </div>
                            <div class="card-block">
                                <center> <h1 class="lead"> <%= link_to travel.title, user_travel_path(@user,travel)%> </h1></center>
                            </div>
                            </br>
                            </br>
                    </li>
                </ul>
            <%end%>
        <%end%>
                        </div>
    </div>
</div>
<%end%>

app/views/travels/new.html.erb
<%= simple_form_for([@user,@travel]) do |f|%>
    <%=f.input :title%>
    <%=f.input :content, rows: 10%>
    Featured Photo:
    <%=f.file_field :featured_image%></br></br>
    Hotspot:
    <%=f.collection_select(:hotspot_id, Hotspot.all, :id, :name)%></br></br>
    <%=f.submit "Share Travel!", class: "btn btn-success"%>
<%end%>

<div>
    Can't find your hotspot in the list? Create your own! <%= link_to "Hotspots", hotspots_path%>
    </div>

app/views/travels/show.html.erb
<hr>
<center><h1 class="travhead"><%=@travel.title%>(<%= link_to @travel.hotspot.name, hotspot_path(@travel.hotspot)%>)<h1></center>
<hr>

<%= @travel.content %>
<hr>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2 class="page-header">Comments</h2>
            <section class="comment-list">
                <% if @travel.comments.any?%>
                    <% @travel.comments.each do |comment| %>
                        <article class="row">
                            <div class="col-md-2 col-sm-2 hidden-xs">
                                <figure class="thumbnail">
                                    <figcaption class="text-center"><%=link_to comment.user.name, user_path(comment.user)%></figcaption>
                                </figure>
                            </div>
                            <div class="col-md-10 col-sm-10">
                                <div class="panel panel-default arrow left">
                                    <div class="panel-body">
                                        <header class="text-left">
                                            <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= comment.created_at.to_date%></time>
                                        </header>
                                        <div class="comment-post">
                                            <p><%= comment.content%></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    <%end%>
                <%end%>
                <div class="container">
                    <div class="row">
                        <div class="col md-6 sm-6">

                            <%= form_for([@user,@travel,@comment]) do |f|%>
                                <div class="from-group">
                                    <%= f.label :comment%>
                                    <%= f.text_area :content, class: "form-control", placeholder: "Write a comment.."%>
                                </div>
                                <div>
                                    <%=f.submit "Add comment", class: "btn btn-success"%>
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>

                >