config/routes.rb
Rails.application.routes.draw do
    post '/rate' => 'rater#create', :as => 'rate'
    get 'acceptions/create'

    devise_for :users, controllers: { registrations: "registrations"}
    root to: 'static_pages#home'
    resources :users do
        resource :info,only: [:show,:new,:create]
        resource :settings, only: [:show,:new,:create]
        resources :photos do
            resources :comments
        end
        resources :travels do
            resources :comments
        end
        resource :contacts

        resources :friendships do
            resource :acceptance , only: [:create, :destroy]
        end
        resources :friends, only: [:index]

        member do
            post "rate"
        end

    end

    resources :hotspots do
        resources :photos do
            resources :comments
        end
        resources :travels, only: [:index]
    end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  belongs_to :travel
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :friend1 , class_name: "User"
    belongs_to :friend2, class_name: "User"

    validates :friend1_id , presence: true
    validates :friend2_id , presence: true

    def accept!
        self.update_attributes(confirmed: true)
    end
end

app/models/heart.rb
class Heart < ActiveRecord::Base
    belongs_to :photo

    belongs_to :user

    validates :user_id , uniqueness: {scope: :photo_id}
end

app/models/hotspot.rb
class Hotspot < ActiveRecord::Base
    has_many :photos
    ratyrate_rateable "stars"
    validates :name, uniqueness: :true
    geocoded_by :address
    after_validation :geocode
    has_many :travels

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

end

app/models/info.rb
class Info < ActiveRecord::Base

  belongs_to :user
  # validates_format_of :dob, :with => /\A(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})\Z/ 




  def if_absent
      self
  end

  def if_present
      yield
      self
  end
end

app/models/noinfo.rb
class Noinfo
    def if_absent
        yield
        self
    end

    def if_present
        self
    end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :hotspot
  has_attached_file :pic, styles: {medium: "300x300", thumbnail: "100x100>", full: "500x500"}
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

  has_many :comments,dependent: :destroy
  default_scope -> {order(created_at: :desc)}

  def set_user(user)
      self.user = user
  end

  def set_hotspot(hotspot, user)
      self.hotspot = hotspot
      self.user = user
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/setting.rb
class Setting
    include ActiveModel::Model

    attr_accessor :info_fb, :info_dob, :info_city , :info_interests

    def save(info)
        info.update_attributes(dob: info_dob, city: info_city , interests: info_interests, fb: info_fb) 
    end
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :user
  has_attached_file :featured_image, styles: {medium: "600x600", thumbnail: "200x200>", full: "500x500"}
  validates_attachment_content_type :featured_image, :content_type => /\Aimage\/.*\Z/
  has_many :comments
  belongs_to :hotspot

  def set_user(user)
      self.user = user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    has_attached_file :avatar, styles: {medium: "300x300", thumbnail: "100x100>"}

    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    has_one :info
    has_many :photos
    has_many :comments,dependent: :destroy
    has_many :travels
    has_many :friendships
    ratyrate_rater

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

    def friends
        Friendship.where("friend1_id = ? OR friend2_id = ?",self.id,self.id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show,:edit]
    def show
            
    end

    def index
        if params[:search]
            @users = User.search(params[:search])
        else
            @users = User.all
        end

    end

    def rate
        @user = User.find(params[:id])
        @num = params[:num].to_i
        if @user.stars
        @user.stars += @num
        else
            @user.stars = 0
            @user.stars += @num
        end
        @user.save
        redirect_to @user
    end




    private

    def set_user
        @user = User.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1><center><i>Users section</i></center></h1>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <%= form_tag(users_path, method: :get) do%>
                        <%= text_field_tag :search,params[:search],placeholder: "Search users"%>
                        <%=submit_tag "Search",class: "btn"%>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>
</br>
<ul class="user-list">
    <% @users.each do |user|%>
        <li><%= link_to user.name, user_path(user)%></li>
    <%end%>
</ul>

app/views/users/show.html.erb
<!-- Main -->
<div id="main">

    <!-- One -->
    <section id="one" class="tiles">
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%= link_to "Info", user_info_path(@user),class: "link"%></h3>
                <p>See user's info.</p>
            </header>
        </article>
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%= link_to "Photos", user_photos_path(@user),class:"link"%></h3>
                <p>See user's uploaded photos.</p>
            </header>
        </article>
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%= link_to "Travels", user_travels_path(@user),class:"link"%></h3>
                <p>See visited places.</p>
            </header>
        </article>
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%= link_to "Reach Out",user_contacts_path(@user) ,class: "link"%></h3>
                <% if current_user == @user%>
                    <p>See who you reached out to.(And vice-versa)</p>
                <%else%>
                    <p>Reach out to <%= @user.name%></p>
                <%end%>
            </header>
        </article>
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%=link_to "Friends" , user_friends_path(@user),class:"link"%></h3>
                <p>See user's friends</p>
            </header>
        </article>
        <article>
            <span class="image">
                <%= image_tag ("pic01.jpg")%>
            </span>
            <header class="major">
                <h3><%=link_to "Settings", new_user_settings_path(current_user)%></h3>
                <p>Only for the owner of this page.</p>
            </header>
        </article>
    </section>

</div>
<div>
    <h1><%= @user.name%>:</h1>
</div>

<div class="propic">
    <center><%= image_tag @user.avatar.url(:medium)%></center>
    </br>
    <%unless current_user == @user %>
        <% unless is_friend?(@user)%>
            <center><%=button_to "Add Friend", user_friendships_path(@user), method: :post, class: "btn btn-info" %></center>
        <%end%>
    <%end%>
</div>

<% unless @user == current_user%>
<div>
    Want to rate <%= @user.name%>'s profile?
    <%= form_for @user, :url => rate_user_path, method: :post do %>
        <%=select_tag(:num,options_for_select([["1"],["2"],["3"],["4"],["5"]]))%>
        <%=submit_tag "Rate"%>
    <%end%>
</div>
<%end%>