config/routes.rb
Rails.application.routes.draw do
    post '/rate' => 'rater#create', :as => 'rate'
    get 'acceptions/create'

    devise_for :users, controllers: { registrations: "registrations"}
    root to: 'static_pages#home'
    resources :users do
        resource :info,only: [:show,:new,:create]
        resource :settings, only: [:show,:new,:create]
        resources :photos do
            resources :comments
        end
        resources :travels do
            resources :comments
        end
        resource :contacts

        resources :friendships do
            resource :acceptance , only: [:create, :destroy]
        end
        resources :friends, only: [:index]

        member do
            post "rate"
        end

    end

    resources :hotspots do
        resources :photos do
            resources :comments
        end
        resources :travels, only: [:index]
    end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
  belongs_to :travel
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :friend1 , class_name: "User"
    belongs_to :friend2, class_name: "User"

    validates :friend1_id , presence: true
    validates :friend2_id , presence: true

    def accept!
        self.update_attributes(confirmed: true)
    end
end

app/models/heart.rb
class Heart < ActiveRecord::Base
    belongs_to :photo

    belongs_to :user

    validates :user_id , uniqueness: {scope: :photo_id}
end

app/models/hotspot.rb
class Hotspot < ActiveRecord::Base
    has_many :photos
    ratyrate_rateable "stars"
    validates :name, uniqueness: :true
    geocoded_by :address
    after_validation :geocode
    has_many :travels

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

end

app/models/info.rb
class Info < ActiveRecord::Base

  belongs_to :user
  # validates_format_of :dob, :with => /\A(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})\Z/ 




  def if_absent
      self
  end

  def if_present
      yield
      self
  end
end

app/models/noinfo.rb
class Noinfo
    def if_absent
        yield
        self
    end

    def if_present
        self
    end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :hotspot
  has_attached_file :pic, styles: {medium: "300x300", thumbnail: "100x100>", full: "500x500"}
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

  has_many :comments,dependent: :destroy
  default_scope -> {order(created_at: :desc)}

  def set_user(user)
      self.user = user
  end

  def set_hotspot(hotspot, user)
      self.hotspot = hotspot
      self.user = user
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/setting.rb
class Setting
    include ActiveModel::Model

    attr_accessor :info_fb, :info_dob, :info_city , :info_interests

    def save(info)
        info.update_attributes(dob: info_dob, city: info_city , interests: info_interests, fb: info_fb) 
    end
end

app/models/travel.rb
class Travel < ActiveRecord::Base
    belongs_to :user
  has_attached_file :featured_image, styles: {medium: "600x600", thumbnail: "200x200>", full: "500x500"}
  validates_attachment_content_type :featured_image, :content_type => /\Aimage\/.*\Z/
  has_many :comments
  belongs_to :hotspot

  def set_user(user)
      self.user = user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    has_attached_file :avatar, styles: {medium: "300x300", thumbnail: "100x100>"}

    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

    has_one :info
    has_many :photos
    has_many :comments,dependent: :destroy
    has_many :travels
    has_many :friendships
    ratyrate_rater

    def self.search(search)
        where("name LIKE ? or name LIKE ?", "%#{search}%", "%#{search}%")
    end

    def friends
        Friendship.where("friend1_id = ? OR friend2_id = ?",self.id,self.id)
    end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :set_source,  :authenticate_user!
    before_action :owned_post,only: [:edit,:update,:destroy]
    def index

        @photo = Photo.new
        @photos = Photo.order('created_at').where(user_id: @user.id)


    end

    def show
        @photo = Photo.find(params[:id])
    end

    def new
        @photo = Photo.new
    end

    def create
        @photo = Photo.new(photo_params)
        @photo.set_user(@user)
        @photo.set_hotspot(@hotspot, current_user)
        if @photo.save
            redirect_to user_path(current_user)
        else
            flash[:notice] = "Your photo could not be saved"
        end
    end

    def edit
        @photo = Photo.find(params[:id])
    end

    def update
        @photo = Photo.find(params[:id])
        @photo.update(photo_params) 
        redirect_to user_photo_path(@user,@photo)
    end

    def destroy
        @photo = Photo.find(params[:id])
        @photo.destroy!
        redirect_to user_path(current_user)
    end



    private

    def set_source
        if params[:user_id]
            @user = User.find(params[:user_id]) 
        else
            @hotspot = Hotspot.find(params[:hotspot_id])
        end
    end

    def photo_params
        params.require(:photo).permit(:pic,:caption)
    end

    def owned_post
        @photo = Photo.find(params[:id])
        unless current_user == @photo.user
            flash[:alert] = "That photo doesnt belong to you"
            redirect_to root_path
        end
    end

    def on_user_path
        if request.original_fullpath.include?("users")
            return true
        end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/photos/_photo.html.erb
<div class="posts-wrapper row">
    <% @photos.each do |photo| %>
        <div class="post">
            <div class="post-head">
                <div class="thumb-img"></div>
                <div class="user-name">
                    <%= link_to photo.user.name, user_path(photo.user) %>
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <%= (Date.current - photo.created_at.to_date).to_i%>days ago
                </div>
            </div>
            <div class="image center-block">
                <%= link_to (image_tag photo.pic.url(:medium), class:'img-responsive'), user_photo_path(@user,photo) %>
            </div>
            <div class="post-bottom">
                <div class="caption">
                    <%= photo.caption %>
                </div>
                <hr>
                <% if photo.comments %>
                    <% photo.comments.each do |comment| %>
                        <div class="comment">
                            <div class="user-name">
                                <%=link_to comment.user.name,user_path(comment.user) %>: <%= comment.content%>
                            </div>
                            <% if comment.user == current_user %>
                                <%= link_to user_photo_comment_path(@user,photo, comment), method: :delete, data: { confirm: "Are you sure?" } do%>
                                    <span class="glyphicon glyphicon-remove delete-comment" aria-hidden="true"></span>
                                <%end%>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
                <div class="comment-like-form row">
                    <div class="like-button col-sm-1">
                        </button>
                        </button>
                    </div>
                    <div class="comment-form col-sm-11">
                        <%= form_for [@user,photo,photo.comments.new] do |f| %>
                            <center> <%= f.text_field :content, placeholder: 'Add a comment...' %></center>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/photos/edit.html.erb
<%= simple_form_for [@user,@photo] do |f|%>
    <%= f.input :caption %>
    <%= f.submit class: "btn btn-default"%>
<%end%>

<br>

<span><%= button_to "Delete", user_photo_path(@user,@photo), method: :delete, class: "btn btn-danger"%><span>

app/views/photos/index.html.erb
<h4>This is the photos section for <strong><i><%=@user.name%></strong></i></h4>.
<div class="row">
    <% if current_user == @user%>
        <div class="col-md-6">
            <div>
                <%= form_for [@user,@photo] do |f|%>
                    <% 15.times do %>
                        &nbsp;
                    <%end%>
                    <%= f.file_field :pic%>
            </div>
            <div>
                </br>
                <% 15.times do %>
                    &nbsp;
                <%end%>
                <%= f.text_area :caption, placeholder: "Caption.."%>
            </div>
            <% 15.times do %>
                &nbsp;
            <%end%>
            <%= button_tag type: 'submit',class: "btn btn-success",id: "register-button" do%>
                <i class="fa fa-camera" aria-hidden="true"> Upload</i>
            <%end%>
        <%end%>
        </div>
    <%end%>
    <div class="col-md-6">
        <%= image_tag @user.avatar.url(:medium), class: "img-cir"%>
    </div>
</div>


<hr/>
<div class="posts-container">
    <%= render 'photo'%>
</div>

app/views/photos/show.html.erb
</br>
<div>
<center><%= image_tag @photo.pic.url(:medium) %></center>
</br>
<center><%= @photo.caption%></center>
</div>
</br>
<div>
<% if @photo.user.id == current_user.id%>
    <div class="text-center edit-links">
        <%=link_to "Cancel", user_photos_path(@user)%>
        |
        <%=link_to "Edit photo", edit_user_photo_path(@user,@photo)%>
<%end%>
</div>